// Base Variations
export const GET_BASE_INFO_SUCCESS = 'GET_BASE_INFO_SUCCESS';
export const UPDATE_BASE_INFO_SUCCESS = 'UPDATE_BASE_INFO_SUCCESS';

// Option Fields
export const GET_FIELDS_INFO_SUCCESS = 'GET_FIELDS_INFO_SUCCESS';
export const ADD_TEXT_FIELD_SUCCESS = 'ADD_TEXT_FIELD_SUCCESS';
export const ADD_CHECKBOX_SUCCESS = 'ADD_CHECKBOX_SUCCESS';
